### PR TITLE
App routing

### PR DESCRIPTION
**Pull request by NadiiaLashtun**

### CODE REVIEW

**Review by mnichols08 — APPROVED** [review]
Nice job finding a solution to the routing issue. I think more commits would make for an easier to debug codebase. But there is no reason to request any changes. I would have used CSSTransitions for the animations between screens but you’ve used tailwind for this so kudos for finding/teaching me an alternative to my known solution.

**Review by mnichols08 — CHANGES_REQUESTED** [review]
Something is happening to cause it so that I am unable to type a different prompt within the text area. We should probably address this before merge, but that is just my opinion.

**Review by KseniiaRiabova — APPROVED** [review]

**Comment by NadiiaLashtun** [comment]
> Something is happening to cause it so that I am unable to type a different prompt within the text area. We should probably address this before merge, but that is just my opinion.

@mnichols08  Fixed when resolving conflict.

**Review by Valeriusdev — APPROVED** [review]
Well done.

**Pull request merged**
